apiVersion: v1
kind: Service
metadata:
  name: guestbookfrontend
  labels:
    app.kubernetes.io/name: guestbookfrontend
    app.kubernetes.io/component: frontend
spec:

  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: guestbookfrontend
    app.kubernetes.io/component: frontend