apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbookfrontend
  labels:
    app.kubernetes.io/name: guestbookfrontend #changed the name
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbookfrontend
      app.kubernetes.io/component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbookfrontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: guestbookfrontend
        image: paulczar/gb-frontend:v5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
