apiVersion: v1
kind: PersistentVolume
metadata:
<<<<<<< HEAD
  name: mongo-pv1-hostpath
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
=======
  name: mongodb-pv-hostpath
spec:
  capacity: 
    storage: 4Gi  # 4Gi storage
  accessModes:
    - ReadWriteOnce
    #added storage class
  storageClassName: localstorage
  persistentVolumeReclaimPolicy: Retain
>>>>>>> staging
  hostPath:
    path: /tmp/mongodb